ACCESSION_DNA_LONG_READS=SRR23234617
ACCESSION_DNA_SHORT_READS=SRX19178152
THREADS=8
OUT_DIR=flye_output
bash download.sh ${ACCESSION_DNA_LONG_READS} ${ACCESSION_DNA_SHORT_READS} ${THREADS}
bash assemble.sh ${ACCESSION_DNA_LONG_READS} ${ACCESSION_DNA_SHORT_READS} ${THREADS} ${OUT_DIR}
